name: Build Android APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Unzip and Build
        run: |
          unzip pk-earn-pro.zip -d project
          find project -name gradlew -exec chmod +x {} \;
          find project -name gradlew -exec {} assembleDebug \;
          # Saari APKs ko root folder mein copy karein
          find project -name "*.apk" -exec cp {} . \;
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: "*.apk"
          
