name: Build Android APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Unzip and Build
        run: |
          unzip pk-earn-pro.zip -d project
          find project -name gradlew -exec chmod +x {} \;
          find project -name gradlew -exec {} assembleDebug \;
          
      - name: List APK files
        run: find . -name "*.apk"
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: project/**/outputs/apk/debug/*.apk
          
